"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var _exportNames = {};
exports.default = void 0;
var _NativeLniReactNative = _interopRequireDefault(require("./NativeLniReactNative"));
var lni = _interopRequireWildcard(require("./generated/lni"));
Object.keys(lni).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  if (key in exports && exports[key] === lni[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function () {
      return lni[key];
    }
  });
});
function _interopRequireWildcard(e, t) { if ("function" == typeof WeakMap) var r = new WeakMap(), n = new WeakMap(); return (_interopRequireWildcard = function (e, t) { if (!t && e && e.__esModule) return e; var o, i, f = { __proto__: null, default: e }; if (null === e || "object" != typeof e && "function" != typeof e) return f; if (o = t ? n : r) { if (o.has(e)) return o.get(e); o.set(e, f); } for (const t in e) "default" !== t && {}.hasOwnProperty.call(e, t) && ((i = (o = Object.defineProperty) && Object.getOwnPropertyDescriptor(e, t)) && (i.get || i.set) ? o(f, t, i) : f[t] = e[t]); return f; })(e, t); }
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }
// Generated by uniffi-bindgen-react-native

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  _NativeLniReactNative.default.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  lni.default.initialize();
  initialized = true;
}

// Export the crates as individually namespaced objects.
var _default = exports.default = {
  lni
};
//# sourceMappingURL=index.js.map