import {
	BACKEND_HOST,
	BACKUPS_SERVER_HOST,
	BACKUPS_SERVER_PUBKEY,
	BLOCKTANK_HOST,
	CHATWOOT_API,
	DEFAULT_BITCOIN_NETWORK,
	E2E,
	ELECTRUM_REGTEST_HOST,
	ELECTRUM_REGTEST_PROTO,
	ELECTRUM_REGTEST_SSL_PORT,
	ELECTRUM_REGTEST_TCP_PORT,
	ENABLE_I18NEXT_DEBUGGER,
	ENABLE_LDK_LOGS,
	ENABLE_MIGRATION_DEBUG,
	ENABLE_REDUX_IMMUTABLE_CHECK,
	ENABLE_REDUX_LOGGER,
	TREASURE_HUNT_HOST,
	WEB_RELAY,
} from '@env';
import { isProtocol } from '../store/types/settings';
import { isBitcoinNetwork } from '../utils/networks';

if (!isBitcoinNetwork(DEFAULT_BITCOIN_NETWORK)) {
	throw new Error(`${DEFAULT_BITCOIN_NETWORK} is not a valid Bitcoin network.`);
}

if (!isProtocol(ELECTRUM_REGTEST_PROTO)) {
	throw new Error(`${ELECTRUM_REGTEST_PROTO} is not a valid protocol.`);
}

if (!BACKEND_HOST) {
	throw new Error('BACKEND_HOST is missing.');
}

if (!BACKUPS_SERVER_HOST || !BACKUPS_SERVER_PUBKEY) {
	throw new Error('BACKUPS_SERVER_HOST or BACKUPS_SERVER_PUBKEY is missing.');
}

export const __JEST__ = process.env.JEST_WORKER_ID !== undefined;

export const __ENABLE_REDUX_LOGGER__ = ENABLE_REDUX_LOGGER === 'true';
export const __ENABLE_MIGRATION_DEBUG__ = ENABLE_MIGRATION_DEBUG === 'true';
export const __ENABLE_REDUX_IMMUTABLE_CHECK__ =
	__DEV__ && ENABLE_REDUX_IMMUTABLE_CHECK
		? ENABLE_REDUX_IMMUTABLE_CHECK === 'true'
		: false;

export const __ENABLE_I18NEXT_DEBUGGER__ = ENABLE_I18NEXT_DEBUGGER === 'true';

export const __ENABLE_LDK_LOGS__ = ENABLE_LDK_LOGS === 'false';

export const __BACKEND_HOST__ = BACKEND_HOST;
export const __BACKUPS_SERVER_HOST__ = BACKUPS_SERVER_HOST;
export const __BACKUPS_SERVER_PUBKEY__ = BACKUPS_SERVER_PUBKEY;

export const __BLOCKTANK_HOST__ = BLOCKTANK_HOST;

export const __DEFAULT_BITCOIN_NETWORK__ = DEFAULT_BITCOIN_NETWORK;

export const __ELECTRUM_REGTEST_HOST__ = ELECTRUM_REGTEST_HOST;
export const __ELECTRUM_REGTEST_SSL_PORT__ = ELECTRUM_REGTEST_SSL_PORT;
export const __ELECTRUM_REGTEST_TCP_PORT__ = ELECTRUM_REGTEST_TCP_PORT;
export const __ELECTRUM_REGTEST_PROTO__ = ELECTRUM_REGTEST_PROTO;

export const __WEB_RELAY__ = WEB_RELAY;
export const __TREASURE_HUNT_HOST__ = TREASURE_HUNT_HOST;
export const __CHATWOOT_API__ = CHATWOOT_API;
export const __E2E__ = E2E === 'true';
